### ISSUE TITLE
Did Travis hallucinate or is there a hidden bug in !n / !-n ?

### ISSUE THREAD

**Issue by lsimonne** [42shpimanmls/42sh#100]
Le build travis a randomly fail sur 2 tests de bang_n - à tester, retester, reretester

**Comment by n0izn0iz** [comment]
Go run les test avec valgrind pour check les erreurs de mémoire

**Comment by pilespin** [comment]
when Travis hallucin use a commit of this kind 770f8db is good for him

**Comment by n0izn0iz** [comment]
T'est sur que c'est du a ça ?

**Comment by pilespin** [comment]
je pense il y a de l'aleatoire dans une mauvaise initialisation plutot.

**Comment by n0izn0iz** [comment]
moi aussi

**Comment by lsimonne** [comment]
j'ai fix les quelques invalid read etc., pull request prochainement

**Comment by n0izn0iz** [comment]
cool

**Comment by n0izn0iz** [comment]
close ?

**Comment by pilespin** [comment]
close
