### ISSUE TITLE
`sys_errlist' is deprecated `use strerror'

### ISSUE THREAD

**Issue by pilespin** [42shpimanmls/42sh#108]
execute_pipeline.c:20: warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead

**Comment by n0izn0iz** [comment]
sur les macs de l'école ?

**Comment by n0izn0iz** [comment]
le problème c'est que strerror et strerror_t sont des fonctions et dans la section 3 des mans (chez moi en tout cas)
donc soit on laisse le warning du compiler soit on fait notre propre (ft_)sys_errlist

**Comment by pilespin** [comment]
ubuntu
