### ISSUE TITLE
Setenv vs export -- both is exported?

### ISSUE THREAD

**Issue by pilespin** [42shpimanmls/42sh#124]

**Comment by lsimonne** [comment]
setenv c'est le export (bash) de csh, non?

**Comment by lsimonne** [comment]
et set/ unset c'est pour les variables locales 
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#set
mais on doit pas le faire ça il me semble

**Comment by n0izn0iz** [comment]
unset doit être fait mais pas set.
Si setenv existe dans csh je suis pour qu'on se base la dessus

**Comment by n0izn0iz** [comment]
@pilespin regarde les issues de chaque builtin, ya les info

**Comment by lsimonne** [comment]
ah d'accord, en fait c'est une des features optionnelles qu'on a choisies, mais dans le sujet ils ont regroupé export et unset en tant que builtins pour les variables locales alors que c'est set/unset, ou j'hallucine?
du coup il faut bien faire un export qui est en fait un set ˆˆ

**Comment by n0izn0iz** [comment]
set c'est un bordel monstre je crois, export moins

**Comment by n0izn0iz** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#export

**Comment by n0izn0iz** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#set
set aussi, avec 9 syntaxes et 11 options ^^

**Comment by n0izn0iz** [comment]
export a 2 syntaxe et une option

**Comment by n0izn0iz** [comment]
close ? @pilespin
