### ISSUE TITLE
ft_getopt

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#126]
Qqun a fait un parser d'options qui suit cette spec ?

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02

**Comment by lsimonne** [comment]
nope, j'ai pas lu la bible pour history ... 
mais je peux le faire si vous voulez

**Comment by n0izn0iz** [comment]
C'est pour les builtins.
 mais pas forcement nécessaire.. Je demandais au cas ou ^^ (genre pour cd ya écrit "The cd utility shall conform to XBD Utility Syntax Guidelines .")

**Comment by n0izn0iz** [comment]
close ou pas du coup ?

**Comment by M5oul** [comment]
close.

**Comment by n0izn0iz** [comment]
par quelle fonction ?

**Comment by n0izn0iz** [comment]
get_option_core
