### ISSUE TITLE
Expansion

### ISSUE THREAD

**Issue by lsimonne** [42shpimanmls/42sh#137]
On est d'accord, on va pas jusqu'à faire les arithmetic expansions et compagnie? Juste un implémentation simple de ${parameter} et le pathname expansion (http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13_03)?

**Comment by n0izn0iz** [comment]
+ le $VAR j'imagine que c'est une composante de la partie optionelle "variables locale"
+ pathname expansion pas obligatoire il me semble
+ tout les autres on oubli a part tilde expansion p'tet^^

**Comment by lsimonne** [comment]
'$[any number of $]' always results to one '$' , is it a problem ?
(in sh $ is actually a variable that returns the pid of the shell)

**Comment by n0izn0iz** [comment]
je pense qu'il faut gérer $$ (partie variables locales du sujet)
Un bon moyen de le faire serait une fonction set_default_variables qui setenv("?", pid) et autres "PWD" "SHLVL" et "_":

```
env -i sh
sh-4.4$ env
PWD=/home/n0iz/Projects/42sh
SHLVL=1
_=/usr/bin/env
```

**Comment by lsimonne** [comment]
#161

**Comment by lsimonne** [comment]
en fait c'est chiant le tilde:
pour les cas ~login il faut utiliser getpwnam() - man 3
je le fais à moitié? càd juste ~/foo, ~ ? ou pas du tout? ou complètement comme théoriquement c'est du bonus?

**Comment by M5oul** [comment]
À moitié c’est bien. Je connais pas `~login`.
Sinon, tant pis si c’est trop chiant s’il s’agit d’un bonus.

**Comment by n0izn0iz** [comment]
a moitié

**Comment by n0izn0iz** [comment]
on peux le faire a la norme avec read("/etc/passwd") mais osef, go pas le faire

**Comment by lsimonne** [comment]
#170
