### ISSUE TITLE
Use generic f() to retrieve options for builtins

### ISSUE THREAD

**Issue by M5oul** [42shpimanmls/42sh#140]
For `env`, `echo` use:
- [This one may be more generic](https://github.com/42shpimanmls/42sh/pull/138/commits/78c2dcaf49d614071ed1630aedc43f24c2aec59d#diff-5aa2439433b0a639a28896ca92ca046b)
- [remove this one](https://github.com/42shpimanmls/42sh/blob/master/srcs/execution/builtins/opt.c)

**Comment by pilespin** [comment]
#126

**Comment by pilespin** [comment]
get_options_core il faut rajoute le -- pour stop les argument

**Comment by pilespin** [comment]
et update is_an_argument

**Comment by pilespin** [comment]
fixed #138 
get_options_core work with is_an_option
