### ISSUE TITLE
Handle '~' substitution to $HOME

### ISSUE THREAD

**Issue by M5oul** [42shpimanmls/42sh#161]
Do we want to handle `cd ~`, `cd ~/projects/42sh`, `ls ~`?
If so, we have to handle substitution from `~` to `$HOME`.

**Comment by lsimonne** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01

**Comment by lsimonne** [comment]
closing, see #137
