### ISSUE TITLE
get_hostname is useless on Mac

### ISSUE THREAD

**Issue by lsimonne** [42shpimanmls/42sh#162]
didn't find how to get the hostname except with uname (in man 3, but since it's a bit of a bonus maybe we can use it ...)
whatever we do about that, we should protect the read syscall! (otherwise errno is set and a message can be wrongly displayed)

**Comment by pilespin** [comment]
si c'est un bonus utilisé des extra peut etre justifiable

**Comment by pilespin** [comment]
si c'est pour le -1 check la valeur du fd avant de read

**Comment by lsimonne** [comment]
oui c'est fait ça

**Comment by pilespin** [comment]
close

**Comment by pilespin** [comment]
uname > uname dans makefile
read uname

**Comment by lsimonne** [comment]
osef, bonus ˆˆ

**Comment by pilespin** [comment]
fixed #182
