### ISSUE TITLE
Bad output echo -n bad_option

### ISSUE THREAD

**Issue by pilespin** [42shpimanmls/42sh#215]
```
$ echo -M5 oul
Bad argument: M5
```
VS
```
>echo -M5 oul
-M5 oul
```

**Comment by lsimonne** [comment]
```
bash-3.2$ echo -n -t
-tbash-3.2$
```

```
[ChezLouise@iMac-de-Louise ~/Documents/42/42sh]$ echo -n -t
-n -t
```

**Comment by pilespin** [comment]
[KO]  "echo -n lol"
 lol
 -n lol

**Comment by M5oul** [comment]
Previous way to handle options with `echo` was good to handle this case.
Now, it's annoying.

**Comment by n0izn0iz** [comment]
tfaçon le '-n' c'est un bonus nan ?

**Comment by M5oul** [comment]
Non, les trois options sont obligatoires.
Ici, le bug et que si la première option est bonne, elle est prise en compte. Si la seconde n’est pas bonne, elle ne l’est pas.
Dans le cas où les deux options ne sont pas bonnes, elles ne sont pas prises en compte.

Perso, je trouve ce point assez pointu. Si le correcteur voit ce problème c’est un pinailleur.
Je l’aurai corrigé, mais ça fait faire un gros chantier juste pour ça.

**Comment by n0izn0iz** [comment]
ben non ya pas d'options a echo en vrai
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html

**Comment by n0izn0iz** [comment]
> The echo utility has not been made obsolescent because of its extremely widespread use in historical applications. Conforming applications that wish to do prompting without <newline> characters or that could possibly be expecting to echo a -n, should use the printf utility derived from the Ninth Edition system.

**Comment by M5oul** [comment]
Let's close this one.
Reopen if not agreed.
