### ISSUE TITLE
SH under OSX

### ISSUE THREAD

**Issue by pilespin** [42shpimanmls/42sh#240]
[KO]  "echo -n lol"
 lol
 -n lol
 [KO]  "exit -99999"
 42sh: wrong exit value: -99999

 DIFFERENT SIGNAL:  42sh=2 vs sh=97
 [KO]  "exit -1"
 42sh: wrong exit value: -1

 DIFFERENT SIGNAL:  42sh=2 vs sh=255
 [KO]  "env -lol ls"
1c1,3
 Usage: env [-i] name[=word]…
 env: illegal option -- l
 usage: env [-iv] [-P utilpath] [-S string] [-u name]
            [name=value ...] [utility [argument ...]]
 DIFFERENT SIGNAL:  42sh=125 vs sh=1

**Comment by n0izn0iz** [comment]
oui ça fait la même chez moi, c'est juste des valeurs de retour différents, ce qui n'est pas standardisé

**Comment by n0izn0iz** [comment]
ton test devrait convertir la valeur de retour en booleen et comparer ça

**Comment by pilespin** [comment]
zero its OK or not?

**Comment by pilespin** [comment]
if (RETURN != 0)
----ERROR

**Comment by n0izn0iz** [comment]
(42sh_exit_status != 0) == (refshell_exit_status != 0)

**Comment by n0izn0iz** [comment]
ou (bool)42sh_exit_status == (bool)refshell_exit_status

**Comment by pilespin** [comment]
pourquoi convertir un bool?

**Comment by n0izn0iz** [comment]
pas compris ta question

**Comment by pilespin** [comment]
> ton test devrait convertir la valeur de retour en booleen et comparer ça

pourquoi convertir un bool?

**Comment by pilespin** [comment]
les command not found 127 il se retrouverait en TRUE ou FALSE

**Comment by n0izn0iz** [comment]
mais c'est pas standardisé ce truc la!

**Comment by n0izn0iz** [comment]
le gros truc chiant c'est qu'on peux plus tester exit

**Comment by n0izn0iz** [comment]
mais on peux faire 2 suites de tests, une qui est stricte sur la valeur de retour et une qui fait le test booleen

**Comment by pilespin** [comment]
je pense que c'est BAD le test boolean

**Comment by n0izn0iz** [comment]
ok mais du coup ça va faire des erreur sur nos sh mais pas sur travis ou vis versa

**Comment by pilespin** [comment]
pourquoi travis il passe

**Comment by n0izn0iz** [comment]
parceque j'ai modifié pour que les valeurs de retour match le shell de travis (retourne 2 quand il y a des erreurs de syntaxe ou d'usage et (% n) ou (2 si n < 0) dans exit)

**Comment by pilespin** [comment]
il y a que le SH de travis qui est en BOOLEEN?

**Comment by n0izn0iz** [comment]
wut??
non, comme tu l'a fait remarquer, les shells envoient tous des valeurs de retour différentes pour certains tests (mais toujours != 0 ou == 0)
Il faudrait faire la validation booléenne pour ces tests la

**Comment by pilespin** [comment]
dans les test il faudrait que je rajoute:
[CK] si c'est pas le meme signal et que les deux sont different de zero

**Comment by n0izn0iz** [comment]
je le fait dans #241 ?

**Comment by pilespin** [comment]
non

**Comment by pilespin** [comment]
#242

**Comment by n0izn0iz** [comment]
#242
