### ISSUE TITLE
Norme

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#26]

**Comment by M5oul** [comment]
Wow, so much work to do on `srcs` folder:
```bash
norminette srcs/**/*.c | grep -v 42 | wc -l
   1165
cat srcs/**/*.c | wc -l
    8312
```

**Comment by M5oul** [comment]
J’ai globalement fait tous les correctifs qui étaient simples à corriger.
J’ai laissé des commentaires qui disaient de faire des modifications.
Ça serait bien que ceux qui les ont mis s’en occupe.
Sinon, il y aura les lignes de débugage à enlever https://github.com/42shpimanmls/42sh/issues/212.
Il devrait rester les 25 lignes par fichier qui risquent de casser des choses et les cinq fonctions par fichiers.

**Comment by pilespin** [comment]
il faut faire des test

**Comment by M5oul** [comment]
> Note for me, remaining todos:

### 5 functions per file
- [ ] `execution/builtins/cd`
- [ ] `expansion/{command_substitution.c,quote_removal.c}`
- [ ] `read_input/edit_input.c`
- [ ] `read_input/event_callbacks/arrows.c `

### 25 lines per function
- [ ] `parse_input`
- [ ] `read_input/editor> vim cursor_vector.c`
- [ ] `utils/add_quotes.c`
- [ ] `utils/option/get_options.c`

**Comment by pilespin** [comment]
Rapport norme
https://pastebin.com/KkPzMgdX
