### ISSUE TITLE
What's happening?

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#268]
Tout le monde il est mort ? @M5oul @lsimonne @pilespin

**Comment by n0izn0iz** [comment]
T'a réussi a valider ton 21sh @M5oul ?
C'est quoi la date du blackhole pour ceux qui l'ont ?

**Comment by M5oul** [comment]
> Tout le monde il est mort ?

Oui, je trouvais les choses calme aussi.
Pour ma part, j’ai bossé la semaine dernière sur un test pour avoir un stage.
Je sais pas ce que fait @pilespin et si @lsimonne est rentrée de vacances.

> T'a réussi a valider ton 21sh @M5oul ?

Non, la norme doit être finie sur le 42sh pour que je puisse valider le 21sh.

> C'est quoi la date du blackhole pour ceux qui l'ont ?

C’est le 25 mai.

**Comment by n0izn0iz** [comment]
Et du coup vous êtes détente par rapport a cette date ou c'est comment ? On le finit ce shell ?

**Comment by M5oul** [comment]
> Et du coup vous êtes détente par rapport a cette date ou c'est comment ?

Oui, on est trop détente.

> On le finit ce shell ?

Il reste quoi à finir pour le 42sh ?

**Comment by pilespin** [comment]
https://github.com/42shpimanmls/42sh/issues

**Comment by pilespin** [comment]
#215

**Comment by M5oul** [comment]
Plus de nouvelles @lsimonne : https://github.com/lsimonne

**Comment by lsimonne** [comment]
j'avoue j'ai un peu beaucoup craqué sur la prolongation des vacances.. mais oui, finissons-le, ce projet ˆˆ

**Comment by n0izn0iz** [comment]
mais du coup ya pas blackhole dans 3 jours ? vous pouvez repousser ?

**Comment by lsimonne** [comment]
ouais je pense, faut juste aller baratiner un peu la pedago je crois, je pense pas qu'ils virent vraiment des gens comme ça - enfin j'espère aha

**Comment by n0izn0iz** [comment]
ok, faudrait vérifier ^^

**Comment by n0izn0iz** [comment]
Du coup vous vous êtes fait aspirer @lsimonne @M5oul ?

**Comment by lsimonne** [comment]
Yes, entretien pour être dévirée mardi à 14h40, donc si tout se passe bien on peut se voir mardi après-midi?

**Comment by n0izn0iz** [comment]
Ok pour moi

**Comment by n0izn0iz** [comment]
Verdict ? @M5oul  tu a eu ton entretien aussi ?

**Comment by M5oul** [comment]
Je vais rencontrer l’équipe pédagogique demain.

**Comment by lsimonne** [comment]
très chelou comme entretien, je pense pas que c'était très déterminant en fait, un one to one avec un petit jeune qui prenait pas de notes... Ils se réunissent (le bocal) et donnent le verdict la semaine prochaine...

**Comment by n0izn0iz** [comment]
Ok.. :/

**Comment by lsimonne** [comment]
salut, j'ai été définitivement exclue de l'école, désolée pour le projet, j'espère que vous pourrez le rendre quand même... Bonne continuation!

**Comment by M5oul** [comment]
De même pour moi.
Je pense que le mieux à faire c’est de demander à la pédago que vous puissiez faire corriger le projet à deux.
Librement

**Comment by n0izn0iz** [comment]
Arggg, je suis désolé pour vous :(
Bonne continuation !
