### ISSUE TITLE
ISIG or not

### ISSUE THREAD

**Issue by pilespin** [42shpimanmls/42sh#283]
with:
ctrl + c  does not propagate to child and not handled by signal()

without:
read stay blocked

**Comment by n0izn0iz** [comment]
désactiver ISIG avant execve?

**Comment by pilespin** [comment]
mon git il colle pas avec github deja

**Comment by pilespin** [comment]
il les puisque il passe par close_termaps() avant d'executé

**Comment by pilespin** [comment]
non peut etre un probleme de close
sa marche une fois mais pas les suivante
