### ISSUE TITLE
Termcaps \n

### ISSUE THREAD

**Issue by ZbTR** [42shpimanmls/42sh#290]
Ctrl bas saute une ligne quand trop de fleches gauche sur la premiere ligne
Ctrl haut a gerer quand ligne au dessus plus courte
Selectionner avec ctrl + b puis aller a la ligne

**Comment by n0izn0iz** [comment]
#308

**Comment by n0izn0iz** [comment]
woops, ctrl-up ctrl-down in multiline not handled

**Comment by n0izn0iz** [comment]
All issues looks fixed
