### ISSUE TITLE
Make works CUnits test on macOS

### ISSUE THREAD

**Issue by M5oul** [42shpimanmls/42sh#32]
To continue https://github.com/42shpimanmls/42sh/pull/20 discussion.
I want to make tests works on 42's macOS.

I installed `automake`:
```bash
brew install automake
Warning: automake-1.15 already installed
```

and it still doesn't works:
```bash
/Users/mazimi/projects/42sh/tests}-> make
BUILDING CUNIT:
tar -xf /Users/mazimi/projects/42sh/tests/CUnit-2.1-3.tar.bz2
cd /Users/mazimi/projects/42sh/tests/CUnit-2.1-3 && mv configure.in configure.ac
cd /Users/mazimi/projects/42sh/tests/CUnit-2.1-3 && aclocal
/bin/sh: aclocal: command not found
make: *** [/Users/mazimi/projects/42sh/tests/CUnit-2.1-3/install/lib/libcunit.a] Error 127
```

I will try to make it works on my GNU/Linux distro.

**Comment by n0izn0iz** [comment]
Fait un "if osx" (no idea comment par contre), pas de aclocal. ça devrait marcher sans, c'était pour silence un warning

**Comment by n0izn0iz** [comment]
ou juste commente le, tfaçon même un re ne rebuild pas la librairie

**Comment by n0izn0iz** [comment]
something something about trying to fix stuff that isn't broken xD

**Comment by lsimonne** [comment]
t'as réussi? j'avais pas vu l'issue.. J'ai un peu galéré à faire fonctionner tout ça aussi mais j'ai pas eu ce problème là ˆˆ
