### ISSUE TITLE
Toue ce qu'il y a dans la section 2 des mans

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#34]
Qqun avait vu que dans les fonctions autorisée il y avait ça ????

EV_SET.2
FD_CLR.2
FD_COPY.2
FD_ISSET.2
FD_SET.2
FD_ZERO.2
_exit.2
accept.2
access.2
acct.2
adjtime.2
aio_cancel.2
aio_error.2
aio_read.2
aio_return.2
aio_suspend.2
aio_write.2
audit.2
auditctl.2
auditon.2
bind.2
brk.2
chdir.2
chflags.2
chmod.2
chown.2
chroot.2
clonefile.2
clonefileat.2
close.2
connect.2
connectx.2
creat.2
disconnectx.2
dup.2
dup2.2
exchangedata.2
execve.2
faccessat.2
fchdir.2
fchflags.2
fchmod.2
fchmodat.2
fchown.2
fchownat.2
fclonefileat.2
fcntl.2
fgetattrlist.2
fgetxattr.2
fhopen.2
flistxattr.2
flock.2
fork.2
fpathconf.2
fremovexattr.2
fsetattrlist.2
fsetxattr.2
fstat.2
fstat64.2
fstatat.2
fstatfs.2
fstatfs64.2
fsync.2
ftruncate.2
futimes.2
getattrlist.2
getattrlistat.2
getattrlistbulk.2
getaudit.2
getaudit_addr.2
getauid.2
getdirentries.2
getdirentriesattr.2
getdtablesize.2
getegid.2
getentropy.2
geteuid.2
getfh.2
getfsstat.2
getgid.2
getgroups.2
gethostuuid.2
getitimer.2
getlogin.2
getpeername.2
getpgid.2
getpgrp.2
getpid.2
getppid.2
getpriority.2
getrlimit.2
getrusage.2
getsid.2
getsockname.2
getsockopt.2
gettimeofday.2
getuid.2
getxattr.2
i386_get_ldt.2
i386_set_ldt.2
intro.2
ioctl.2
issetugid.2
kevent.2
kevent64.2
kevent_qos.2
kill.2
killpg.2
kqueue.2
lchown.2
link.2
linkat.2
listen.2
listxattr.2
lseek.2
lstat.2
lstat64.2
madvise.2
mincore.2
minherit.2
mkdir.2
mkdirat.2
mkfifo.2
mknod.2
mlock.2
mmap.2
mount.2
mprotect.2
msync.2
munlock.2
munmap.2
nanosleep.2
nfsclnt.2
nfssvc.2
open.2
openat.2
pathconf.2
pipe.2
poll.2
posix_madvise.2
posix_spawn.2
posix_spawnp.2
pread.2
profil.2
pselect.2
pthread_kill.2
pthread_setugid_np.2
pthread_sigmask.2
ptrace.2
pwrite.2
quotactl.2
read.2
readlink.2
readlinkat.2
readv.2
reboot.2
recv.2
recvfrom.2
recvmsg.2
removexattr.2
rename.2
renameat.2
renameatx_np.2
renamex_np.2
revoke.2
rmdir.2
sbrk.2
searchfs.2
select.2
sem_close.2
sem_open.2
sem_post.2
sem_trywait.2
sem_unlink.2
sem_wait.2
semctl.2
semget.2
semop.2
send.2
sendfile.2
sendmsg.2
sendto.2
setattrlist.2
setaudit.2
setaudit_addr.2
setauid.2
setegid.2
seteuid.2
setgid.2
setgroups.2
setitimer.2
setlogin.2
setpgid.2
setpgrp.2
setpriority.2
setregid.2
setreuid.2
setrlimit.2
setsid.2
setsockopt.2
settimeofday.2
setuid.2
setxattr.2
shm_open.2
shm_unlink.2
shmat.2
shmctl.2
shmdt.2
shmget.2
shutdown.2
sigaction.2
sigaltstack.2
sigblock.2
sigmask.2
sigpause.2
sigpending.2
sigprocmask.2
sigsetmask.2
sigstack.2
sigsuspend.2
sigvec.2
sigwait.2
socket.2
socketpair.2
stat.2
stat64.2
statfs.2
statfs64.2
symlink.2
symlinkat.2
sync.2
truncate.2
umask.2
undelete.2
unlink.2
unlinkat.2
unmount.2
utimes.2
vfork.2
wait.2
wait3.2
wait4.2
waitpid.2
write.2
writev.2

**Comment by pilespin** [comment]
en fait, tout quoi!

**Comment by n0izn0iz** [comment]
> With posix_spawn(), the executable file is specified as a  pathname  (which
>        can be absolute or relative).

**Comment by n0izn0iz** [comment]
'fin execvpe quoi ^^

**Comment by n0izn0iz** [comment]
> The  execlp(),  execvp(),  and execvpe() functions duplicate the actions of the shell in searching for an exe‐
>        cutable file if the specified filename does not contain a slash (/) character.

ça c'est fait xD
