### ISSUE TITLE
Prompt dynamique

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#35]
Ce serait possible de faire un prompt modifiable dans le code ? Je peux le faire si c'est possible et que personne est déter'

**Comment by pilespin** [comment]
le prompt c'est simple mais la base elle buggé

**Comment by n0izn0iz** [comment]
La base ?

**Comment by pilespin** [comment]
il saute des ligne avant le dernier charactere

**Comment by n0izn0iz** [comment]
Qui il ? et le dernier char de ?

**Comment by pilespin** [comment]
le cursor monte de une ligne quand il il a plus de place sur la ligne

**Comment by n0izn0iz** [comment]
ha, nan mais c'est juste pour que quand il y a une erreur résolvable de break_input ou parse_input ça affiche ce que c'est un peu comme zsh (<quote> a la place du prompt pour un quote non fermé par exemple)

**Comment by n0izn0iz** [comment]
je peux juste remplacer le ft_putstr(PROMPT) par un ft_putstr(ed->prompt) ?

**Comment by pilespin** [comment]
si tu veut

**Comment by pilespin** [comment]
ed->prompt = get_variable(PWD)
