### ISSUE TITLE
Problem with cursor left and cursor right when there is a newline in a history line

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#53]
```
 ✘ n0iz@arch-vm  ~/Projects/42sh   master  ./42sh
[/home/n0iz/Projects/42sh]$ foo '
```
entrée
```
quote> bar'
```
entrée
```
<syntax_tree>
command: foo '\nbar'
</syntax_tree>
```
puis faire flèche haut
```
[/home/n0iz/Projects/42sh]$ foo '
bar'
```
Puis essayer de revenir au début de la ligne, puis essayer de dépasser la fin de la ligne. @pilespin  je t'en parlais heir

**Comment by pilespin** [comment]
je regarde

**Comment by pilespin** [comment]
virer les \n avant de les stocker dans l'historique ?

**Comment by n0izn0iz** [comment]
On peux faire ça pour |, && et || mais pas pour ' et ". C'est un des intérêt des quotes, de pouvoir foutre des newline dans un argument ou autre.
Il suffit de modifier les fonction check_if_margin_*  je peux le faire si tu veux.

**Comment by pilespin** [comment]
ok
