### ISSUE TITLE
Segv history

### ISSUE THREAD

**Issue by pilespin** [42shpimanmls/42sh#55]
./42sh
entrée puis fleche haut

Program received signal SIGSEGV, Segmentation fault.
0x0000000000405784 in str_to_list (ed=0x60c338 <get_editor.ed>, str=0x0)
    at srcs/read_input/event_callbacks/history.c:18
18		while (*str)

**Comment by n0izn0iz** [comment]
strtrim qui renvoi NULL au lieu de "" en conjonction de str_to_list qui plante sur str == NULL
== problem

**Comment by n0izn0iz** [comment]
faut changer l'un ou l'autre

**Comment by n0izn0iz** [comment]
je pencherai pour changer str_to_list qui plante sur null

**Comment by n0izn0iz** [comment]
#48 ?
