### ISSUE TITLE
Gestion correcte [...] des tabulations.

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#65]
4e ligne de la partie obligatoire du sujet, pour l'instant on les ignore

**Comment by pilespin** [comment]
on les ignore ou plutot faire l'autocompletion?

**Comment by n0izn0iz** [comment]
Je pense qu'il faudrait pouvoir gérer une tabulation dans la ligne déjà (ctrl-v puis tab dans sh).
L'autocompletion on oublie a mon avis vu le temps qui est passé déjà.

**Comment by n0izn0iz** [comment]
#307

**Comment by n0izn0iz** [comment]
#307
