### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#72]

**Comment by n0izn0iz** [comment]
race condition pour la valeur de retour au lieu de la valeur de retour de la dernière commande

**Comment by lsimonne** [comment]
cat /dev/urandom | head -c 100

**Comment by lsimonne** [comment]
j'ai passé un p'tit moment là-dessus et j'ai pas trouvé la solution ... si quelqu'un l'a ! 
@n0izn0iz @M5oul @pilespin

**Comment by pilespin** [comment]
sa bug aussi sur sh

**Comment by lsimonne** [comment]
sh affiche juste le prompt sans retour à la ligne avant, nous il quitte pas cat

**Comment by lsimonne** [comment]
en fait le process principal wait ses enfants, mais head du coup c'est un petit enfant - donc faudrait juste wait pour la dernière commande de la pipeline

**Comment by n0izn0iz** [comment]
if faut faire une fonction wait_for_pipeline_childs(int last_child_pid)

**Comment by lsimonne** [comment]
#155
