### ISSUE TITLE
pasting in terminal and shift-insert are not working

### ISSUE THREAD

**Issue by n0izn0iz** [42shpimanmls/42sh#81]
Has something to do with the way the editor reads input

**Comment by pilespin** [comment]
comment tu utilise ton shift insert?

**Comment by pilespin** [comment]
j'ai insert sur la meme touche que suppr

**Comment by pilespin** [comment]
non c'est bon

**Comment by pilespin** [comment]
ctrl shift v

**Comment by pilespin** [comment]
solved in #83
