### ISSUE TITLE
Réunion \n in history and termcaps bugs #60

### ISSUE THREAD

**Issue by pilespin** [42shpimanmls/42sh#84]
@n0izn0iz @lsimonne @M5oul

**Comment by lsimonne** [comment]
salut ! désolée j'avais plus de choses à faire que prévu... je suis dispo demain ou jeudi pour la réunion. En attendant je m'y remets!

**Comment by n0izn0iz** [comment]
je ne suis pas dispo demain mais sinon oui

**Comment by pilespin** [comment]
@n0izn0iz @lsimonne @M5oul
Du monde aujourd'hui?

**Comment by n0izn0iz** [comment]
Moi je peux venir quand vous voulez

**Comment by pilespin** [comment]
moi aussi mais il faut @lsimonne pour l'historique.

**Comment by lsimonne** [comment]
je suis un peu dans le mal depuis hier, mais je peux me bouger en fin d'aprem..

**Comment by n0izn0iz** [comment]
demain du coup ?

**Comment by pilespin** [comment]
c'est la crise des place

**Comment by lsimonne** [comment]
maintenant ou demain c'est ok pour moi, mais demain j'ai une réunion à 17h donc je devrai partir vers 16h

(pour le problème en question, ça vient du fait que tu recalcules la position du curseur en fonction de strlen(line), alors que dans le cas d'un \n au milieu il faut rajouter tout le vide, non?)

**Comment by pilespin** [comment]
le probleme c'est que:
quand on a une commande sur plusieurs ligne a chaque fois que l'on fais fleche du haut sa return la meme ligne avec la derniere ligne en moins

**Comment by n0izn0iz** [comment]
on dit demain 14h ?

Pour le \n, on est pas obligé de le gérer dans l'historique: on pourrais découper a tout les \n et considérer qu'une ligne c'est une ligne. ça simplifie bcp de choses pour l'édition de ligne.

**Comment by n0izn0iz** [comment]
c'est le but de la réunion, choisir entre ça et changer la façon dont on gére l'édition pour faire comme on avait prévu a la base.

**Comment by lsimonne** [comment]
ok on voit ça demain
