### ISSUE TITLE
execvp isn't in section 2 of man!

### ISSUE THREAD

**Issue by lsimonne** [42shpimanmls/42sh#94]
et c'est lui qui établit /usr/bin:/bin comme PATH par défaut, d'où le comportement de bash

**Comment by n0izn0iz** [comment]
ok c'est quoi les fonction sur la page execve du coup ?

**Comment by pilespin** [comment]
man execvpe est pas sur les dump

**Comment by pilespin** [comment]
et dans le man de execve sur c'est mac il y a que execve

**Comment by n0izn0iz** [comment]
oki

**Comment by lsimonne** [comment]
ouais y'a que execve
